version: "3.4"

name: ${APP:-app}

services:
  nginx:
    image: app_nginx
    container_name: ${APP:-app}_nginx
    build:
      context: .
      target: nginx
    ports:
      - "${NGINX_PORT:-9000}:9000"

  php:
    image: app_php
    container_name: ${APP:-app}
    build:
      context: .
      target: php
#    TODO: project volume

  mysql:
    image: mysql:8.1
    container_name: ${APP:-app}_mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        MYSQL_USER: ${MYSQL_USER:-app}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
#    TODO: mysql volume