version: "3.4"

services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "9000:9000"
    networks:
        - app-network

  php:
    build:
      context: .
      target: php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge