version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    networks:
        - app-network
    volumes:
      - ./:/var/www/app

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - ./:/var/www/app

networks:
  app-network:
    driver: bridge