version: "3.4"

name: app

services:
    nginx:
        image: app_nginx
        container_name: app_nginx
        build:
            context: .
            target: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/

    php:
        image: app_php
        container_name: app_php
        build:
            context: .
            target: php
        volumes:
            - ./:/var/www/app
        networks:
            - main_network

    mysql:
        image: mysql:8.1
        container_name: app_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        volumes:
            - ./docker/mysql_volume/:/var/lib/mysql